# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Work/opalkelly_syzygy/adc/Vivado-LTC2264-12/SZG-ADC-LTC2264-12.srcs/sources_1/ip/enc_clk/enc_clk.xci
# IP: The module: 'enc_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/opalkelly_syzygy/adc/Vivado-LTC2264-12/SZG-ADC-LTC2264-12.gen/sources_1/ip/enc_clk/enc_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'enc_clk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work/opalkelly_syzygy/adc/Vivado-LTC2264-12/SZG-ADC-LTC2264-12.gen/sources_1/ip/enc_clk/enc_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'enc_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work/opalkelly_syzygy/adc/Vivado-LTC2264-12/SZG-ADC-LTC2264-12.gen/sources_1/ip/enc_clk/enc_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'enc_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Work/opalkelly_syzygy/adc/Vivado-LTC2264-12/SZG-ADC-LTC2264-12.srcs/sources_1/ip/enc_clk/enc_clk.xci
# IP: The module: 'enc_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/opalkelly_syzygy/adc/Vivado-LTC2264-12/SZG-ADC-LTC2264-12.gen/sources_1/ip/enc_clk/enc_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'enc_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work/opalkelly_syzygy/adc/Vivado-LTC2264-12/SZG-ADC-LTC2264-12.gen/sources_1/ip/enc_clk/enc_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'enc_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work/opalkelly_syzygy/adc/Vivado-LTC2264-12/SZG-ADC-LTC2264-12.gen/sources_1/ip/enc_clk/enc_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'enc_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
